version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - my_network
    environment:
      - MONGO_URL=mongodb://mongo:27017/users_db
  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - my_network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
